apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "endy-chart.fullname" . }}
  labels:
    {{- include "endy-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "endy-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "endy-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "endy-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            # - name: SECRET_USERNAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: example-mongodb-admin-my-user
            #       key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-user-password
                  key: password
            # - name: SECRET_CONNECTION_STRING_STANDARD
            #   valueFrom:
            #     secretKeyRef:
            #       name: example-mongodb-admin-my-user
            #       key: connectionString.standard
            # - name: SECRET_CONNECTION_STRING_SRV
            #   valueFrom:
            #     secretKeyRef:
            #       name: example-mongodb-admin-my-user
            #       key: connectionString.standardSrv
            - name: SECRET_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-creds
                  key: app.txt
            - name: SECRET_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-creds
                  key: bot.txt
            - name: ORG
              valueFrom:
                secretKeyRef:
                  name: org
                  key: org.txt
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
