repos:
  -   repo: https://github.com/pre-commit/mirrors-eslint
      rev: '993fa54833f6c858f4922b2540c1cb4424c542fb'  # Commit v8.46.0
      hooks:
      -   id: eslint
          additional_dependencies:
          -   eslint@8.46.0
          -   eslint-config-standard@17.1.0
          -   eslint-plugin-import@2.28.0
          -   eslint-plugin-n@16.0.1
          -   eslint-plugin-promise@6.1.1