version: "3.8"
services:
  endybot:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
  db:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    ##Uncomment the comments below for your local db to be persistent 
    #volumes: 
    #  - endybot_db:/data/db

#volumes:
#  endybot_db: